trigger:
  - main
  - pipeline

pool:
  vmImage: 'windows-2019'

name: 0.0.$(rev:r)

steps:
  - task: Maven@3
    displayName: 'Maven validate'
    inputs:
      mavenPomFile: '$(system.defaultworkingdirectory)/pom.xml'
      goals: 'clean validate'

  - task: Maven@3
    displayName: 'Maven Test'
    inputs:
      mavenPomFile: '$(System.DefaultWorkingDirectory)/pom.xml'
      goals: 'clean test'
      options: '-DBASE_URL=$(BASE_URL) -Dgroups=Smoke'
      publishJUnitResults: true
      testResultsFiles: '$(System.DefaultWorkingDirectory)/target/surefire-reports/TEST-*.xml'
      testRunTitle: 'HCM-API-Test'
      javaHomeOption: 'JDKVersion'
      mavenVersionOption: 'Default'
      mavenAuthenticateFeed: false
      effectivePomSkip: false
      sonarQubeRunAnalysis: false
    continueOnError: true

  - task: PowerShell@2
    displayName: "Generate Allure Report"
    inputs:
      targetType: 'inline'
      script: |
        # Write your PowerShell commands here.
        iwr -useb get.scoop.sh -outfile 'install.ps1'
        .\install.ps1 -RunAsAdmin

        scoop install allure

        allure generate
      workingDirectory: '$(System.DefaultWorkingDirectory)'
    condition: succeededOrFailed()

  - task: ArchiveFiles@2
    displayName: 'Archive Files'
    inputs:
        rootFolderOrFile: '$(System.DefaultWorkingDirectory)/allure-report'
        archiveFile: '$(Build.ArtifactStagingDirectory)/HCM-API_Test-Report.zip'
    condition: succeededOrFailed()

  - task: SendEmail@0
    displayName: 'Send an email with subject HCM Module - Smoke Test - QA'
    inputs:
      To: 'abbasr@atlashxm.com,akhilc@atlashxm.com,syeds@atlashxm.com,sundarap.contractor@elementsgs.com,emil.g@thinkpalm.com,dhruvt@atlashxm.com,shahanab.contractor@elementsgs.com,'
      From: 'azuredevops@elementsgs.com'
      Subject: 'HCM API Test - QA'
      Body: |
        Hello,
        API test Dashboard URL:
        https://technology-internal.visualstudio.com/Atlas-HCM/_build/results?buildId=$(Build.BuildId)&view=ms.vss-test-web.build-test-results-tab
      Attachment: '$(Build.ArtifactStagingDirectory)/HCM-API_Test-Report.zip'
      SmtpServer: 'smtp.office365.com'
      SmtpPort: '25'
      SmtpUsername: 'azuredevops@elementsgs.com'
      SmtpPassword: '$(PASSWORD)'
      STARTTLS: true
    condition: succeededOrFailed()

  - task: CalromEmailReport@1
    inputs:
      sendMailConditionConfig: 'Always'
      subject: '[{environmentStatus}] {passPercentage} API tests passed in HCM Module'
      toAddress: 'abbasr@atlashxm.com;abdulq.contractor@elementsgs.com;aswinis.contractor@elementsgs.com;akhilc@atlashxm.com;syeds@atlashxm.com;sundarap.contractor@elementsgs.com;emil.g@thinkpalm.com;dhruvt@atlashxm.com;shaheryarr.contractor@elementsgs.com;shahanab.contractor@elementsgs.com;'
      defaultDomain: 'elementsgs.com'
      includeResultsStr: '1, 2'
      groupTestResultsBy: 'run'
      includeCommits: false
      maxTestFailuresToShow: '30'
      includeOthersInTotal: true
      usePreviousEnvironment: false
      enableTLS: true
      smtpConnectionEndpoint: 'SMTPforQAreport'
    condition: succeededOrFailed()